### ISSUE TITLE
Issues

### ISSUE THREAD

**Issue by SebastianJuch** [arthurwolf/Octofab#5]
- Uploading data to SD or locally do not work
- Setting an offset do not work

**Comment by arthurwolf** [comment]
About upload, I tested it here and it seemed to work. Does it not work at
all, or is there some problem more specifically ?

What are offsets ?

On Wed, Dec 16, 2015 at 10:40 PM, SebastianJuch notifications@github.com
wrote:

> - Uploading data to SD or locally do not work
> - Setting an offset do not work
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/arthurwolf/Octofab/issues/5.

## 

Courage et bonne humeur.

**Comment by SebastianJuch** [comment]
I tried to upload a simple gcode file several times, from Workstation, Laptop and Tablet.

Offset ... Temeratur offset. If i connect my thermistor it shows the Temperatur correct but i can not set an offset. e.g. +1°C  or -1 °C

**Comment by arthurwolf** [comment]
@SebastianJuch Uploading now works ( using "upload to SD" ).

About offset, I see it in the interface, but I don't think that's something Smoothie supports, or what the feature is for ...

**Comment by SebastianJuch** [comment]
Great work. The Offset is for an Temperatur offset. If your thermistor gives you an Temperatur that is e.g. 3 degrees over or under the real Temperatur, you are able so set an Offset to get the right Temperatur. Hope you understand what i mean;-)
